#! /bin/sh 

case $# in                          # faz match no numero de argumentos
    0) set `date`; m=$2; y=$6;      # se sem argumentos: usa a data atual, `date` = $(date)
	case $m in                      # da match no valor em EN de m e troca pra PT 
	    Feb) m=Fev;; 
	    Apr) m=Abr;; 
	    May) m=Mai;; 
	    Aug) m=Ago;; 
	    Sep) m=Set;; 
	    Oct) m=Out;; 
	    Dec) m=Dez;; 
	esac;; 
    1) m=$1; set `date`; y=$6;;     # se 1 argumento: guarda o mes, pega o ano com `date`
    *) m=$1; y=$2 ;;                # se 2 argumentos: guarda mes e ano 
esac 
case $m in                          # da match no valor do mes e armazena como numero 
    jan*|Jan*) m=1;; 
    fev*|Fev*) m=2;; 
    mar*|Mar*) m=3;; 
    abr*|Abr*) m=4;; 
    mai*|Mai*) m=5;; 
    jun*|Jun*) m=6;; 
    jul*|Jul*) m=7;; 
    ago*|Ago*) m=8;; 
    set*|Set*) m=9;; 
    out*|Out*) m=10;; 
    nov*|Nov*) m=11;; 
    dez*|Dez*) m=12;; 
    [1-9]|10|11|12) ;;              # se ja e um numero, nao faz nada 
    *) y=$m; m="";;                 # se sem match, guarda o valor vazio pro mes 
esac 
/usr/bin/cal $m $y                  # printa a data no calendario (comando `cal`)

