#! /bin/sh

# se os argumentos $1, $2, ... existirem (nao forem nulos),
# sao armazenados em param1, param2, ... 
test -n "$1" && param1=$1
test -n "$2" && param2=$2
test -n "$3" && param3=$3
test -n "$4" && param4=$4

# se param1 nao for setado, usa "rs"
echo "1o resultado do teste:${param1-rs} com param1 = $param1"
# se param2 nao for setado, usa "pa" e faz param2="pa"
echo "2o resultado do teste:${param2=pa} com param2 = $param2"
# se param3 FOR setado, usa "to"
echo "3o resultado do teste:${param3+to} com param3 = $param3"
# se param4 nao for setado, imprime a mensagem e sai com status de erro
echo "4o resultado do teste:${param4?Quarto parâmetro não iniciado} com param4 = $param4"

